from zendesk.utils.helpers import get_ticket_by_id


def test_zendesk_get_api_call():
    testcases = [
        {
            "id": 25,
            "expected_response": {
                "url": "https://zccanaxyz1.zendesk.com/api/v2/tickets/25.json",
                "id": 25,
                "external_id": None,
                "via": {
                    "channel": "api",
                    "source": {"from": {}, "to": {}, "rel": None},
                },
                "created_at": "2021-11-26T00:00:55Z",
                "updated_at": "2021-11-26T00:00:55Z",
                "type": None,
                "subject": "voluptate dolor deserunt ea deserunt",
                "raw_subject": "voluptate dolor deserunt ea deserunt",
                "description": "Consectetur eiusmod pariatur ullamco voluptate irure sunt magna cillum velit irure commodo culpa ipsum in. Nulla non exercitation dolor quis minim deserunt ad consequat officia ullamco irure consectetur anim mollit. Cupidatat exercitation cillum excepteur culpa consectetur ad adipisicing exercitation est amet ullamco id eiusmod tempor. Aliqua quis irure culpa tempor mollit veniam. Fugiat aliquip duis non sit id eu ea anim sit ea aliqua et dolor.\n\nCulpa culpa culpa id proident dolor magna ipsum dolor irure mollit proident culpa. Officia Lorem veniam dolor sit commodo id consequat ex qui enim veniam. Laboris velit excepteur sit sit anim nulla exercitation.",
                "priority": None,
                "status": "open",
                "recipient": None,
                "requester_id": 1902326529344,
                "submitter_id": 1902326529344,
                "assignee_id": 1902326529344,
                "organization_id": 1900081685144,
                "group_id": 4411212176539,
                "collaborator_ids": [],
                "follower_ids": [],
                "email_cc_ids": [],
                "forum_topic_id": None,
                "problem_id": None,
                "has_incidents": False,
                "is_public": True,
                "due_at": None,
                "tags": ["do", "est", "labore"],
                "custom_fields": [],
                "satisfaction_rating": None,
                "sharing_agreement_ids": [],
                "fields": [],
                "followup_ids": [],
                "ticket_form_id": 1900004186464,
                "brand_id": 1900001329924,
                "allow_channelback": False,
                "allow_attachments": True,
            },
        },
        {
            "id": 32,
            "expected_response": {
                "url": "https://zccanaxyz1.zendesk.com/api/v2/tickets/32.json",
                "id": 32,
                "external_id": None,
                "via": {
                    "channel": "api",
                    "source": {"from": {}, "to": {}, "rel": None},
                },
                "created_at": "2021-11-26T00:00:59Z",
                "updated_at": "2021-11-26T00:00:59Z",
                "type": None,
                "subject": "velit irure elit incididunt non",
                "raw_subject": "velit irure elit incididunt non",
                "description": "Fugiat ad qui in incididunt duis exercitation veniam. Cupidatat elit ex mollit sunt ullamco magna voluptate ea Lorem anim cupidatat Lorem ullamco pariatur. Id ex et aliquip proident ut quis dolore labore anim id dolore minim. Aliqua dolor pariatur in id veniam do nostrud cillum consequat consequat non veniam ea. Ut cupidatat ex fugiat cupidatat.\n\nAliqua fugiat dolore magna occaecat proident adipisicing anim aute tempor eiusmod ad Lorem reprehenderit non. Ut eu aliquip eu nostrud aute mollit tempor sit dolor aliquip duis eiusmod veniam. Ullamco tempor tempor in cillum dolore esse tempor nostrud qui ullamco. Do culpa sit sunt deserunt voluptate enim eiusmod veniam. Amet fugiat esse amet aute velit reprehenderit magna incididunt. Ea non elit magna ad fugiat duis Lorem ea. Sint amet qui ea sit Lorem ullamco laborum est deserunt nisi proident eu eiusmod voluptate.",
                "priority": None,
                "status": "open",
                "recipient": None,
                "requester_id": 1902326529344,
                "submitter_id": 1902326529344,
                "assignee_id": 1902326529344,
                "organization_id": 1900081685144,
                "group_id": 4411212176539,
                "collaborator_ids": [],
                "follower_ids": [],
                "email_cc_ids": [],
                "forum_topic_id": None,
                "problem_id": None,
                "has_incidents": False,
                "is_public": True,
                "due_at": None,
                "tags": ["consequat", "cupidatat", "occaecat"],
                "custom_fields": [],
                "satisfaction_rating": None,
                "sharing_agreement_ids": [],
                "fields": [],
                "followup_ids": [],
                "ticket_form_id": 1900004186464,
                "brand_id": 1900001329924,
                "allow_channelback": False,
                "allow_attachments": True,
            },
        },
        {"id": 12390129012, "expected_response": None},
    ]

    for t in testcases:
        resp = get_ticket_by_id(t.get("id"))
        assert resp == t.get("expected_response")
